spring:
  application:
    name: external-configuration
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mikhail0-0/configuration.git
          default-label: main
server:
  port: 8888

